server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: http://order-service:8081
              predicates:
                - Path=/api/v1/orders/**