spring:
  application:
    name: payment-service

  profiles:
    active: elk

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8084

logging:
  structured:
    format:
      console: ecs
    json:
      stacktrace:
        max-throwable-depth: 30
        max-length: 2048
  pattern:
    console: "%d{IS08601} %-5level [%thread] %X{traceId} %X{spanId} %logger{36} - %msg%n"
  level:
    root: info
    org.hibernate.sql: debug
    com.simplecoding.paymentservice: debug

management:
  otlp:
    metrics:
      export:
        enabled: false

  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true

  observations:
    annotations:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,1s,2s

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4318/v1/traces

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full

url:
  order-service: ${ORDER_SERVICE_URL}
  inventory-service: ${INVENTORY_SERVICE_URL}

resilience4j:
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 200ms
        exponential-backoff-multiplier: 2.0
        exponential-max-wait-duration: 10s
        randomized-wait-factor: 0.3
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - com.simplecoding.paymentservice.exception.ReservationCompleteFailedException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - java.lang.IllegalStateException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException

    instances:
      orderService:
        base-config: default
        max-attempts: 4

      inventoryService:
        base-config: default
        max-attempts: 3

  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      orderService:
        base-config: default
        sliding-window-size: 10
        failure-rate-threshold: 40
        minimum-number-of-calls: 10
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - com.simplecoding.paymentservice.exception.OrderConfirmationFailedException
        ignore-exceptions:
          - java.lang.IllegalStateException
          - java.lang.IllegalArgumentException

      inventoryService:
        base-config: default
        sliding-window-size: 10
        failure-rate-threshold: 40
        minimum-number-of-calls: 10
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - com.simplecoding.paymentservice.exception.ReservationCompleteFailedException
        ignore-exceptions:
          - java.lang.IllegalStateException
          - java.lang.IllegalArgumentException

  timelimiter:
    instances:
      orderService:
        timeout-duration: 2000ms
        cancel-running-future: true

      inventoryService:
        timeout-duration: 2000ms
        cancel-running-future: true

  bulkhead:
    configs:
      default:
        max-concurrent-calls: 10
        max-wait-duration: 0
        writable-stack-trace-enabled: true
        event-consumer-buffer-size: 100

    instances:
      orderService:
        base-config: default
        max-concurrent-calls: 5
        max-wait-duration: 0

      inventoryService:
        base-config: default
        max-concurrent-calls: 5
        max-wait-duration: 0

info:
  app:
    name: "E-Commerce-App(payment-service)"
    version: "1.0.0"
    description: "xxx"