spring:
  profiles:
    active: elk
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:order_service_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8081

logging:
  structured:
    format:
      console: ecs
    json:
      stacktrace:
        max-throwable-depth: 30
        max-length: 2048
  pattern:
    console: "%d{IS08601} %-5level [%thread] %X{traceId} %X{spanId} %logger{36} - %msg%n"
  level:
    root: info
    com.simplecoding.orderservice: debug

management:
  otlp:
    metrics:
      export:
        enabled: false

  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true

  observations:
    annotations:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,1s,2s

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4318/v1/traces

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full

info:
  app:
    name: "E-Commerce-App(order-service)"
    version: "1.0.0"
    description: "xxx"

url:
  notification-service: ${NOTIFICATION_SERVICE_URL}
  payment-service: ${PAYMENT_SERVICE_URL}