spring:
  application:
    name: product-service

  profiles:
    active: elk

  elasticsearch:
    uris: http://${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}
    username: ${ELASTIC_USER:admin}
    password: ${ELASTIC_PASSWORD:admin}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:products_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  structured:
    format:
      console: ecs
    json:
      stacktrace:
        max-throwable-depth: 30
        max-length: 2048
  pattern:
    console: "%d{IS08601} %-5level [%thread] %X{traceId} %X{spanId} %logger{36} - %msg%n"
  level:
    root: info
    org.hibernate.sql: debug
    com.simplecoding.productservice: debug

management:
  otlp:
    metrics:
      export:
        enabled: false

  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true

  observations:
    annotations:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,1s,2s

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4318/v1/traces

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full


info:
  app:
    name: "E-Commerce-App(product-service)"
    version: "1.0.0"
    description: "xxx"

server:
  port: 8085